### ISSUE TITLE
Include a comment section

### ISSUE THREAD

**Issue by strzibny** [strzibny/invoice_printer#2]
Documents should be able to include a printable comment at the end.

**Comment by HCLarsen** [comment]
On a multi-page invoice, should the comments appear at the bottom of the first page (below the list of items), or at the bottom of the last page, below the total?

**Comment by strzibny** [comment]
I would personaly it prefer at the end on the last page.  Thoughts?

**Comment by SheepD** [comment]
I would also prefer it at the end of the last page, however, under what instance would the invoice generated have more than one page?

**Comment by HCLarsen** [comment]
I worked in sales before becoming a developer, and I've seen it both ways. I don't have a preference, so I thought I'd ask. 

@Sheepd, the invoice would have more than one page if there were too many line items to fit on one page.

**Comment by SheepD** [comment]
@HCLarsen thanks. though the reason to have the comments at the bottom of the first page would be to allow the sender/recipient to see the comments immediately, right?

**Comment by HCLarsen** [comment]
Basically, that would be the logic behind that.

**Comment by SheepD** [comment]
@strzibny would it be fine to submit a pr for this?

**Comment by HCLarsen** [comment]
Forgive me for being new to this, but what's a "pr?"

**Comment by SheepD** [comment]
@HCLarsen thats short for Pull Request, its basically a feature on github used to contribute code. I'm asking permission to submit a PR for this to make sure that no one is already working on it. Cause no one wants to duplicate someone else' work and waste their efforts

you can refer to this document for more details about it https://help.github.com/articles/using-pull-requests/

**Comment by HCLarsen** [comment]
@SheepD Ok, yes, I know about Pull Requests. I've just never heard anyone abbreviate it to PR before.

**Comment by strzibny** [comment]
Yes, feel free to submit PR. That would be great.
