### ISSUE TITLE
item date

### ISSUE THREAD

**Issue by agc57** [strzibny/invoice_printer#25]
Is it possible to add a Date field to the "item" so that each item can have a date associated with it?
I am trying to use it for a consulting type invoice, and date of service is critical for the invoice.

**Comment by strzibny** [comment]
Would renaming some other unused field work for you? For the next version I am tinkering with the idea that all item's properties are just numbered columns without names.

What I mean is you can use `tax2` field for a date *now*. Or do you need one more field to be there?

**Comment by strzibny** [comment]
Thanks, definitely useful feedback!

**Comment by strzibny** [comment]
I am thinking I will add extra optional field after the name to address this. There might be more optional fields later, but I guess this is sufficient for a lot of use-cases, easy to implement and I don't break compatibility for 1.x versions. (We can add more optionals later and people could avoid using pre-defined  fields this way if they want. I am not really up to loose the semantics altogether yet.)

As for the Buyer/Seller boxes I will create a separate issue later. I would like to support more use-cases there too.

**Comment by strzibny** [comment]
You can already switch to buyer & seller boxes and provide early feedback with the following 2.0 release:
https://rubygems.org/gems/invoice_printer/versions/2.0.0.alpha1
