### ISSUE TITLE
Is it possible to extract server into a separate gem?

### ISSUE THREAD

**Issue by ixti** [strzibny/invoice_printer#26]
IMO serve functionality does not belong to this gem itself. It would be awesome to extract it into `invoice_printer_server` so that `puma` and `roda` dependencies will be moved away as well. :D

**Comment by strzibny** [comment]
I was thinking about it (because of the dependencies), however what won me over for now is practicality (it's not as popular gem so far so is it worth the effort?).

I was too thinking about using Ruby stdlib and Puma only if it's installed, do you think that would be enough?

**Comment by ixti** [comment]
That will be enough, especially if web-related parts will not be required by main require. :D

**Comment by strzibny** [comment]
There are not required now, only the dependencies get installed. Anyway I am more inclined to split it for 2.x series.

**Comment by ixti** [comment]
fwiw my team is moving to puma... so it won't be an issue for us soon anyway ;))

**Comment by strzibny** [comment]
The first release without Puma and Roda dependencies is here: https://rubygems.org/gems/invoice_printer/versions/2.0.0.alpha1

**Comment by ixti** [comment]
Thank you!
