### ISSUE TITLE
Hard to discover options / configurations

### ISSUE THREAD

**Issue by combinatorist** [strzibny/invoice_printer#47]
The only way I've found options for the json document is one CLI input example, but it's not clear whether those are all the options, whether they are extensible, etc.

Am I missing some documentation or should I just read the code?

**Comment by strzibny** [comment]
Do you mean https://github.com/strzibny/invoice_printer/blob/master/docs/COMMAND_LINE.md or something else?

Happy to improve the docs.

**Comment by combinatorist** [comment]
Yes, I believe it was that page. I extracted the json argument from the bottom and prettified it as a template for possible arguments. It would have been nice just to read them in the docs.

In theory, I could probably have infered them from the ruby code, but that is a lot slower and less universal for people than pretty json or actual docs.

Does that make sense?

**Comment by strzibny** [comment]
I think I understand. The full example is mentioned here https://github.com/strzibny/invoice_printer/blob/master/docs/LIBRARY.md, but not specifically broken down into list of options. I think I will make one more page for features in general.
