### ISSUE TITLE
Keeping some information private

### ISSUE THREAD

**Issue by combinatorist** [strzibny/invoice_printer#48]
I have shared tax and bank info separately with my clients and would rather not repeat it in every emailed invoice. However, if I don't put a bank account number, the invoice says "Payment in cash", but I would rather specify "By bank deposit" or nothing at all.

**Comment by combinatorist** [comment]
It sounds like it might be possible with "sublabels" (https://github.com/strzibny/invoice_printer/blob/master/lib/invoice_printer.rb#L47) but those only seem available to Ruby documents and you have to use JSON for the CLI.

**Comment by combinatorist** [comment]
NVM, I can see now in the CLI help where you can change the labels: https://github.com/strzibny/invoice_printer/blob/master/docs/COMMAND_LINE.md

**Comment by combinatorist** [comment]
This is resolved in my mind, but could be clearer in the docs.

**Comment by strzibny** [comment]
Perfect, do you think this could be improved? Feel free to send a PR.

**Comment by combinatorist** [comment]
FWIW, I think the term `label` didn't register for me as a way to configure what is or isn't shown. I probably first interpreted it as address labels, like you would put on the outside of the envelope if you were mailing it. Perhaps, it used to be a narrow use case and then you turned it into a general config.

**Comment by combinatorist** [comment]
Just made a small PR to help clarify what you mean by labels on the main README.

**Comment by combinatorist** [comment]
It also might help to organize the feature list on the main readme as I've done above so people can find what they're looking for.
