### ISSUE TITLE
additional notes run off the page

### ISSUE THREAD

**Issue by combinatorist** [strzibny/invoice_printer#49]
It appears the template only leaves room for one line of notes. If you write too much, it will word wrap, but the additional lines of words won't appear on the page. If you use explicit new lines in the note section than those lines won't appear either.

**Comment by semicolonandsons** [comment]
I'm also getting the exact same bug. If I put in the following code

```ruby
    invoice = InvoicePrinter::Document.new(
      ...
      note: ""Jack K\n123 Fake Street""
    )
```

Only "Jack K" will display in the note.

**Comment by strzibny** [comment]
It's probably because the position is fixed and there is no space.  We could support longer notes by adjusting the initial position based on what's in the note. I agree that this might be needed in the wild.

**Comment by strzibny** [comment]
Done! You can check `master` if it does what you need. I did not limit the number of lines for now.
