### ISSUE TITLE
Allow an optional background image

### ISSUE THREAD

**Issue by drhenner** [strzibny/invoice_printer#5]
Title says it all.  

Also, I didn't look at the code but what does the PDF look like if you have 200 items?

**Comment by strzibny** [comment]
Not a bad suggestion and PR def welcome.

And to answer your question, the table will continue on the next page and pages become numbered.

**Comment by gbalbuena** [comment]
Working on it

**Comment by strzibny** [comment]
Released as `0.0.8`. Thank you @gbalbuena.
