### ISSUE TITLE
is there a way to style the invoice? 

### ISSUE THREAD

**Issue by slopeofhope81** [strzibny/invoice_printer#63]
I want to apply different styles so that each invoice can have a different makeover. Is it possible out of the box?

**Comment by strzibny** [comment]
Hello,

no, you have to manually tweak it (patch it) to do what you want. The idea up until now was to offer only one style. For v3.0 I am thinking we could support some options for tweaking styling, not sure yet.

**Comment by slopeofhope81** [comment]
@strzibny yea i ended up forking. thanks!
