### ISSUE TITLE
Simplify Document Class

### ISSUE THREAD

**Issue by HCLarsen** [strzibny/invoice_printer#7]
The instance variables that describe the provider and purchaser are identical, providing a lot of repetition in the attr_reader calls, and the initialize method. It should be possible to create a class that describes both of these items, and store them as @provider and @purchaser within the Document class. This would certainly clean up the code, as well as make it easier for users to call Document.new. If you agree that this is useful, I would like to work on it myself.

**Comment by strzibny** [comment]
Hi @HCLarsen it is true they are same now and I have nothing against the change. If you will work on it, you are also free to rename 'ic' and 'dic' to something like 'id' to be more generic (IC is a term coming from Czech legislation). Also don't forget on changing comments and README.

**Comment by HCLarsen** [comment]
@strzibny I've never heard the terms 'ic' or 'dic,' so perhaps you could explain them to me. I don't want to rename them to something that makes no sense.

Also, I was wondering about the wording of 'provider.' In North American business, the common terms are 'seller' or 'vendor.' How do you feel about using one of those instead of provider?

**Comment by strzibny** [comment]
@HCLarsen so `ic` and `dic` are identification numbers for the purposes of paying some taxes (translation is "tax identification number"). I suspect more legislation require some kind of identification number/string. That's why I would like to rename it to something like `id` or `tax_id`. I wish I would know more legislations but I don't.

I tried to look up the terminology for the provider and perhaps vendor could work better. What the rest of the English world use (UK, AU, CA)?

I definitely want to fix the naming before `1.0.0` so the help is appreciated.

**Comment by HCLarsen** [comment]
Ok, that makes sense. Here in Canada, it depends upon the province. In Ontario, we used to have 2 numbers, one for federal tax, and an optional one for provincial. Now, we just have one. Americans, I believe they only have one number, which they call the IRS#. Perhaps we could name these tax_id1 and tax_id2, in order to cover the places that have 2 numbers.

**Comment by strzibny** [comment]
Yep, let's rename this first to `provider_tax_id` and `provider_tax_id2` and then let's rename provider itself. Do you wish to work on the rename?

On the original matter of refactoring I would still wait for others to express their opinion. In the meantime can you comment here some pseudo code of how you imagine this to work from the point of the public API? Even though people will have this info in various objects, the original design is "just pass the values and get this done". As you can see here: https://github.com/strzibny/invoicebar/blob/master/app/models/invoice_bar/invoice_pdf.rb

**Comment by HCLarsen** [comment]
Sure. If I understand that example correctly, the retooling would look like this. 

`
    def printable_invoice
      InvoicePrinter::Document.new(
        number: @invoice.number.to_s,
        provider: @invoice.user,
        purchaser: @invoice.purchaser,
        issue_date: @invoice.issue_date.to_s,
        due_date: @invoice.due_date.to_s,
        total: @invoice.amount.to_s,
        bank_account_number: @invoice.account_bank_account_number.to_s,
        account_iban: @invoice.account_iban.to_s,
        account_swift: @invoice.account_swift.to_s,
        items: printable_items
      )
end
`

Even better, we could make it possible to create the user instance from the ActiveRecord User model that you have in this example. In that case, we could have code like this:

`
@user = InvoicePrinter::Entity.new
@user.load_from_active_record(User.find(1))
`

**Comment by HCLarsen** [comment]
Sure. If I understand that example correctly, the retooling would look like this:

`def printable_invoice 
    InvoicePrinter::Document.new( 
        number: @invoice.number.to_s, 
        provider: @invoice.user, 
        purchaser: @invoice.purchaser, 
        issue_date: @invoice.issue_date.to_s, 
        due_date: @invoice.due_date.to_s, 
        total: @invoice.amount.to_s, 
        bank_account_number: @invoice.account_bank_account_number.to_s, 
        account_iban: @invoice.account_iban.to_s, 
        account_swift: @invoice.account_swift.to_s, 
        items: printable_items ) 
end`

**Comment by HCLarsen** [comment]
Sure. If I understand that example correctly, the retooling would look like this.

def printable_invoice 
    InvoicePrinter::Document.new( 
        number: @invoice.number.to_s, 
        provider: @invoice.user, 
        purchaser: @invoice.purchaser, 
        issue_date: @invoice.issue_date.to_s, 
        due_date: @invoice.due_date.to_s, 
        total: @invoice.amount.to_s, 
        bank_account_number: @invoice.account_bank_account_number.to_s, 
        account_iban: @invoice.account_iban.to_s, 
        account_swift: @invoice.account_swift.to_s, 
        items: printable_items ) 
end

Even better, we could make it possible to create the user instance from the ActiveRecord User model that you have in this example. In that case, we could have code like this:

@user = InvoicePrinter::Entity.new 
@user.load_from_active_record(User.find(1))

**Comment by HCLarsen** [comment]
Sure. If I understand that example correctly, the retooling would look like this.

```
def printable_invoice 
    InvoicePrinter::Document.new( 
        number: @invoice.number.to_s, 
        provider: @invoice.user, 
        purchaser: @invoice.purchaser, 
        issue_date: @invoice.issue_date.to_s, 
        due_date: @invoice.due_date.to_s, 
        total: @invoice.amount.to_s, 
        bank_account_number: @invoice.account_bank_account_number.to_s, 
        account_iban: @invoice.account_iban.to_s, 
        account_swift: @invoice.account_swift.to_s, 
        items: printable_items 
    ) 
end
```

Even better, we could make it possible to create the user instance from the ActiveRecord User model that you have in this example. In that case, we could have code like this:

```
@user = InvoicePrinter::Entity.new 
@user.load_from_active_record(User.find(1))
```

**Comment by HCLarsen** [comment]
I also had another thought. When changing the initialize method of the Document class with this Entity class (or whatever we call it), do we want to do it in one step, or do you want to add a deprecation warning in the next release, and then on the full 1.0.0 release, the old attributes will be removed?

**Comment by HCLarsen** [comment]
Oh, and yes, I'll work on the rename. That shouldn't take long after all.

**Comment by HCLarsen** [comment]
Have there been any further thoughts or opinions on this?

**Comment by strzibny** [comment]
There wasn't. I believe it's not needed yet, the interface is simple to use and that was the goal.

**Comment by strzibny** [comment]
Since we now allow to build the documents with JSON I believe you can build the documents by combining various chunks just fine. Perhaps it might be even the recommended way in the future. Closing for now.
